# Generated by Django 4.2.6 on 2023-11-19 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_Rest', '0002_rename_contraseña_cuenta_empleado_contrasena'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre_Usuario', models.CharField(max_length=30)),
                ('Contrasena', models.CharField(max_length=60)),
                ('Correo_Electronico', models.EmailField(max_length=254)),
                ('Edad', models.IntegerField()),
                ('Comuna', models.CharField(max_length=30)),
                ('Numero_Telefonico', models.CharField(max_length=15)),
                ('Genero', models.CharField(max_length=10)),
            ],
        ),
    ]
